
name: amlvae

channels: 
    - pytorch 
    - nvidia 
    - pyg
    - conda-forge
    - defaults 

dependencies:
    - python=3.12
    - matplotlib
    - pytorch
    - pytorch-cuda
    - seaborn
    - scikit-learn
    - h5py
    - scipy
    - numpy
    - statsmodels
    - pip
    - pip:
        - ipykernel
        - umap-learn
        - -e .
